[package]
name = "whatsmeow-nchat"
version = "0.1.0"
edition = "2021"

[dependencies]
whatsmeow-nchat-sys.path = "../whatsmeow-nchat-sys"
thiserror = "2"
tokio = { version = "1", features = ["sync"] }
